netbox/dcim/urls.py
from django.urls import path

from extras.views import ObjectChangeLogView, ImageAttachmentEditView
from ipam.views import ServiceCreateView
from secrets.views import secret_add
from . import views
from .models import (
    Cable, ConsolePort, ConsoleServerPort, Device, DeviceRole, DeviceType, FrontPort, Interface, Manufacturer, Platform,
    PowerFeed, PowerPanel, PowerPort, PowerOutlet, Rack, RackGroup, RackReservation, RackRole, RearPort, Region, Site,
    VirtualChassis,
)

app_name = 'dcim'
urlpatterns = [

    # Regions
    path(r'regions/', views.RegionListView.as_view(), name='region_list'),
    path(r'regions/add/', views.RegionCreateView.as_view(), name='region_add'),
    path(r'regions/import/', views.RegionBulkImportView.as_view(), name='region_import'),
    path(r'regions/delete/', views.RegionBulkDeleteView.as_view(), name='region_bulk_delete'),
    path(r'regions/<int:pk>/edit/', views.RegionEditView.as_view(), name='region_edit'),
    path(r'regions/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='region_changelog', kwargs={'model': Region}),

    # Sites
    path(r'sites/', views.SiteListView.as_view(), name='site_list'),
    path(r'sites/add/', views.SiteCreateView.as_view(), name='site_add'),
    path(r'sites/import/', views.SiteBulkImportView.as_view(), name='site_import'),
    path(r'sites/edit/', views.SiteBulkEditView.as_view(), name='site_bulk_edit'),
    path(r'sites/delete/', views.SiteBulkDeleteView.as_view(), name='site_bulk_delete'),
    path(r'sites/<slug:slug>/', views.SiteView.as_view(), name='site'),
    path(r'sites/<slug:slug>/edit/', views.SiteEditView.as_view(), name='site_edit'),
    path(r'sites/<slug:slug>/delete/', views.SiteDeleteView.as_view(), name='site_delete'),
    path(r'sites/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='site_changelog', kwargs={'model': Site}),
    path(r'sites/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='site_add_image', kwargs={'model': Site}),

    # Rack groups
    path(r'rack-groups/', views.RackGroupListView.as_view(), name='rackgroup_list'),
    path(r'rack-groups/add/', views.RackGroupCreateView.as_view(), name='rackgroup_add'),
    path(r'rack-groups/import/', views.RackGroupBulkImportView.as_view(), name='rackgroup_import'),
    path(r'rack-groups/delete/', views.RackGroupBulkDeleteView.as_view(), name='rackgroup_bulk_delete'),
    path(r'rack-groups/<int:pk>/edit/', views.RackGroupEditView.as_view(), name='rackgroup_edit'),
    path(r'rack-groups/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackgroup_changelog', kwargs={'model': RackGroup}),

    # Rack roles
    path(r'rack-roles/', views.RackRoleListView.as_view(), name='rackrole_list'),
    path(r'rack-roles/add/', views.RackRoleCreateView.as_view(), name='rackrole_add'),
    path(r'rack-roles/import/', views.RackRoleBulkImportView.as_view(), name='rackrole_import'),
    path(r'rack-roles/delete/', views.RackRoleBulkDeleteView.as_view(), name='rackrole_bulk_delete'),
    path(r'rack-roles/<int:pk>/edit/', views.RackRoleEditView.as_view(), name='rackrole_edit'),
    path(r'rack-roles/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackrole_changelog', kwargs={'model': RackRole}),

    # Rack reservations
    path(r'rack-reservations/', views.RackReservationListView.as_view(), name='rackreservation_list'),
    path(r'rack-reservations/edit/', views.RackReservationBulkEditView.as_view(), name='rackreservation_bulk_edit'),
    path(r'rack-reservations/delete/', views.RackReservationBulkDeleteView.as_view(), name='rackreservation_bulk_delete'),
    path(r'rack-reservations/<int:pk>/edit/', views.RackReservationEditView.as_view(), name='rackreservation_edit'),
    path(r'rack-reservations/<int:pk>/delete/', views.RackReservationDeleteView.as_view(), name='rackreservation_delete'),
    path(r'rack-reservations/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackreservation_changelog', kwargs={'model': RackReservation}),

    # Racks
    path(r'racks/', views.RackListView.as_view(), name='rack_list'),
    path(r'rack-elevations/', views.RackElevationListView.as_view(), name='rack_elevation_list'),
    path(r'racks/add/', views.RackEditView.as_view(), name='rack_add'),
    path(r'racks/import/', views.RackBulkImportView.as_view(), name='rack_import'),
    path(r'racks/edit/', views.RackBulkEditView.as_view(), name='rack_bulk_edit'),
    path(r'racks/delete/', views.RackBulkDeleteView.as_view(), name='rack_bulk_delete'),
    path(r'racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path(r'racks/<int:pk>/edit/', views.RackEditView.as_view(), name='rack_edit'),
    path(r'racks/<int:pk>/delete/', views.RackDeleteView.as_view(), name='rack_delete'),
    path(r'racks/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rack_changelog', kwargs={'model': Rack}),
    path(r'racks/<int:rack>/reservations/add/', views.RackReservationCreateView.as_view(), name='rack_add_reservation'),
    path(r'racks/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='rack_add_image', kwargs={'model': Rack}),

    # Manufacturers
    path(r'manufacturers/', views.ManufacturerListView.as_view(), name='manufacturer_list'),
    path(r'manufacturers/add/', views.ManufacturerCreateView.as_view(), name='manufacturer_add'),
    path(r'manufacturers/import/', views.ManufacturerBulkImportView.as_view(), name='manufacturer_import'),
    path(r'manufacturers/delete/', views.ManufacturerBulkDeleteView.as_view(), name='manufacturer_bulk_delete'),
    path(r'manufacturers/<slug:slug>/edit/', views.ManufacturerEditView.as_view(), name='manufacturer_edit'),
    path(r'manufacturers/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='manufacturer_changelog', kwargs={'model': Manufacturer}),

    # Device types
    path(r'device-types/', views.DeviceTypeListView.as_view(), name='devicetype_list'),
    path(r'device-types/add/', views.DeviceTypeCreateView.as_view(), name='devicetype_add'),
    path(r'device-types/import/', views.DeviceTypeBulkImportView.as_view(), name='devicetype_import'),
    path(r'device-types/edit/', views.DeviceTypeBulkEditView.as_view(), name='devicetype_bulk_edit'),
    path(r'device-types/delete/', views.DeviceTypeBulkDeleteView.as_view(), name='devicetype_bulk_delete'),
    path(r'device-types/<int:pk>/', views.DeviceTypeView.as_view(), name='devicetype'),
    path(r'device-types/<int:pk>/edit/', views.DeviceTypeEditView.as_view(), name='devicetype_edit'),
    path(r'device-types/<int:pk>/delete/', views.DeviceTypeDeleteView.as_view(), name='devicetype_delete'),
    path(r'device-types/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='devicetype_changelog', kwargs={'model': DeviceType}),

    # Console port templates
    path(r'device-types/<int:pk>/console-ports/add/', views.ConsolePortTemplateCreateView.as_view(), name='devicetype_add_consoleport'),
    path(r'device-types/<int:pk>/console-ports/delete/', views.ConsolePortTemplateBulkDeleteView.as_view(), name='devicetype_delete_consoleport'),
    path(r'console-port-templates/<int:pk>/edit/', views.ConsolePortTemplateEditView.as_view(), name='consoleporttemplate_edit'),

    # Console server port templates
    path(r'device-types/<int:pk>/console-server-ports/add/', views.ConsoleServerPortTemplateCreateView.as_view(), name='devicetype_add_consoleserverport'),
    path(r'device-types/<int:pk>/console-server-ports/delete/', views.ConsoleServerPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_consoleserverport'),
    path(r'console-server-port-templates/<int:pk>/edit/', views.ConsoleServerPortTemplateEditView.as_view(), name='consoleserverporttemplate_edit'),

    # Power port templates
    path(r'device-types/<int:pk>/power-ports/add/', views.PowerPortTemplateCreateView.as_view(), name='devicetype_add_powerport'),
    path(r'device-types/<int:pk>/power-ports/delete/', views.PowerPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_powerport'),
    path(r'power-port-templates/<int:pk>/edit/', views.PowerPortTemplateEditView.as_view(), name='powerporttemplate_edit'),

    # Power outlet templates
    path(r'device-types/<int:pk>/power-outlets/add/', views.PowerOutletTemplateCreateView.as_view(), name='devicetype_add_poweroutlet'),
    path(r'device-types/<int:pk>/power-outlets/delete/', views.PowerOutletTemplateBulkDeleteView.as_view(), name='devicetype_delete_poweroutlet'),
    path(r'power-outlet-templates/<int:pk>/edit/', views.PowerOutletTemplateEditView.as_view(), name='poweroutlettemplate_edit'),

    # Interface templates
    path(r'device-types/<int:pk>/interfaces/add/', views.InterfaceTemplateCreateView.as_view(), name='devicetype_add_interface'),
    path(r'device-types/<int:pk>/interfaces/edit/', views.InterfaceTemplateBulkEditView.as_view(), name='devicetype_bulkedit_interface'),
    path(r'device-types/<int:pk>/interfaces/delete/', views.InterfaceTemplateBulkDeleteView.as_view(), name='devicetype_delete_interface'),
    path(r'interface-templates/<int:pk>/edit/', views.InterfaceTemplateEditView.as_view(), name='interfacetemplate_edit'),

    # Front port templates
    path(r'device-types/<int:pk>/front-ports/add/', views.FrontPortTemplateCreateView.as_view(), name='devicetype_add_frontport'),
    path(r'device-types/<int:pk>/front-ports/delete/', views.FrontPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_frontport'),
    path(r'front-port-templates/<int:pk>/edit/', views.FrontPortTemplateEditView.as_view(), name='frontporttemplate_edit'),

    # Rear port templates
    path(r'device-types/<int:pk>/rear-ports/add/', views.RearPortTemplateCreateView.as_view(), name='devicetype_add_rearport'),
    path(r'device-types/<int:pk>/rear-ports/delete/', views.RearPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_rearport'),
    path(r'rear-port-templates/<int:pk>/edit/', views.RearPortTemplateEditView.as_view(), name='rearporttemplate_edit'),

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from netbox.views import APIRootView, HomeView, SearchView
from users.views import LoginView, LogoutView
from .admin import admin_site

schema_view = get_schema_view(
    openapi.Info(
        title="NetBox API",
        default_version='v2',
        description="API to access NetBox",
        terms_of_service="https://github.com/netbox-community/netbox",
        license=openapi.License(name="Apache v2 License"),
    ),
    validators=['flex', 'ssv'],
    public=True,
)

_patterns = [

    # Base views
    path(r'', HomeView.as_view(), name='home'),
    path(r'search/', SearchView.as_view(), name='search'),

    # Login/logout
    path(r'login/', LoginView.as_view(), name='login'),
    path(r'logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path(r'circuits/', include('circuits.urls')),
    path(r'dcim/', include('dcim.urls')),
    path(r'extras/', include('extras.urls')),
    path(r'ipam/', include('ipam.urls')),
    path(r'secrets/', include('secrets.urls')),
    path(r'tenancy/', include('tenancy.urls')),
    path(r'user/', include('users.urls')),
    path(r'virtualization/', include('virtualization.urls')),

    # API
    path(r'api/', APIRootView.as_view(), name='api-root'),
    path(r'api/circuits/', include('circuits.api.urls')),
    path(r'api/dcim/', include('dcim.api.urls')),
    path(r'api/extras/', include('extras.api.urls')),
    path(r'api/ipam/', include('ipam.api.urls')),
    path(r'api/secrets/', include('secrets.api.urls')),
    path(r'api/tenancy/', include('tenancy.api.urls')),
    path(r'api/virtualization/', include('virtualization.api.urls')),
    path(r'api/docs/', schema_view.with_ui('swagger'), name='api_docs'),
    path(r'api/redoc/', schema_view.with_ui('redoc'), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(), name='schema_swagger'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path(r'media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Admin
    path(r'admin/', admin_site.urls),

]

if settings.WEBHOOKS_ENABLED:
    _patterns += [
        path(r'admin/webhook-backend-status/', include('django_rq.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        path(r'__debug__/', include(debug_toolbar.urls)),
    ]

if settings.METRICS_ENABLED:
    _patterns += [
        path('', include('django_prometheus.urls')),
    ]

# Prepend BASE_PATH
urlpatterns = [
    path(r'{}'.format(settings.BASE_PATH), include(_patterns))
]

handler500 = 'utilities.views.server_error'

netbox/secrets/api/urls.py
from rest_framework import routers

from . import views


class SecretsRootView(routers.APIRootView):
    """
    Secrets API root view
    """
    def get_view_name(self):
        return 'Secrets'


router = routers.DefaultRouter()
router.APIRootView = SecretsRootView

# Field choices
router.register(r'_choices', views.SecretsFieldChoicesViewSet, basename='field-choice')

# Secrets
router.register(r'secret-roles', views.SecretRoleViewSet)
router.register(r'secrets', views.SecretViewSet)

# Miscellaneous
router.register(r'get-session-key', views.GetSessionKeyViewSet, basename='get-session-key')
router.register(r'generate-rsa-key-pair', views.GenerateRSAKeyPairViewSet, basename='generate-rsa-key-pair')

app_name = 'secrets-api'
urlpatterns = router.urls

netbox/secrets/urls.py
from django.urls import path

from extras.views import ObjectChangeLogView
from . import views
from .models import Secret, SecretRole

app_name = 'secrets'
urlpatterns = [

    # Secret roles
    path(r'secret-roles/', views.SecretRoleListView.as_view(), name='secretrole_list'),
    path(r'secret-roles/add/', views.SecretRoleCreateView.as_view(), name='secretrole_add'),
    path(r'secret-roles/import/', views.SecretRoleBulkImportView.as_view(), name='secretrole_import'),
    path(r'secret-roles/delete/', views.SecretRoleBulkDeleteView.as_view(), name='secretrole_bulk_delete'),
    path(r'secret-roles/<slug:slug>/edit/', views.SecretRoleEditView.as_view(), name='secretrole_edit'),
    path(r'secret-roles/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='secretrole_changelog', kwargs={'model': SecretRole}),

    # Secrets
    path(r'secrets/', views.SecretListView.as_view(), name='secret_list'),
    path(r'secrets/import/', views.SecretBulkImportView.as_view(), name='secret_import'),
    path(r'secrets/edit/', views.SecretBulkEditView.as_view(), name='secret_bulk_edit'),
    path(r'secrets/delete/', views.SecretBulkDeleteView.as_view(), name='secret_bulk_delete'),
    path(r'secrets/<int:pk>/', views.SecretView.as_view(), name='secret'),
    path(r'secrets/<int:pk>/edit/', views.secret_edit, name='secret_edit'),
    path(r'secrets/<int:pk>/delete/', views.SecretDeleteView.as_view(), name='secret_delete'),
    path(r'secrets/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='secret_changelog', kwargs={'model': Secret}),

]

netbox/templates/secrets/secret.html
{% extends '_base.html' %}
{% load static %}
{% load custom_links %}
{% load helpers %}
{% load secret_helpers %}

{% block header %}
    <div class="row noprint">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'secrets:secret_list' %}">Secrets</a></li>
                <li><a href="{% url 'secrets:secret_list' %}?role={{ secret.role.slug }}">{{ secret.role }}</a></li>
                <li>{{ secret.device }}{% if secret.name %} ({{ secret.name }}){% endif %}</li>
            </ol>
        </div>
    </div>
    <div class="pull-right noprint">
        {% if perms.secrets.change_secret %}
            <a href="{% url 'secrets:secret_edit' pk=secret.pk %}" class="btn btn-warning">
                <span class="fa fa-pencil" aria-hidden="true"></span>
                Edit this secret
            </a>
        {% endif %}
        {% if perms.secrets.delete_secret %}
            <a href="{% url 'secrets:secret_delete' pk=secret.pk %}" class="btn btn-danger">
                <span class="fa fa-trash" aria-hidden="true"></span>
                Delete this secret
            </a>
        {% endif %}
    </div>
    <h1>{% block title %}{{ secret }}{% endblock %}</h1>
    {% include 'inc/created_updated.html' with obj=secret %}
    <div class="pull-right noprint">
        {% custom_links secret %}
    </div>
    <ul class="nav nav-tabs">
        <li role="presentation"{% if not active_tab %} class="active"{% endif %}>
            <a href="{{ secret.get_absolute_url }}">Secret</a>
        </li>
        {% if perms.extras.view_objectchange %}
            <li role="presentation"{% if active_tab == 'changelog' %} class="active"{% endif %}>
                <a href="{% url 'secrets:secret_changelog' pk=secret.pk %}">Changelog</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Secret Attributes</strong>
            </div>
            <table class="table table-hover panel-body">
                <tr>
                    <td>Device</td>
                    <td>
                        <a href="{% url 'dcim:device' pk=secret.device.pk %}">{{ secret.device }}</a>
                    </td>
                </tr>
                <tr>
                    <td>Role</td>
                    <td>{{ secret.role }}</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>{{ secret.name|placeholder }}</td>
                </tr>
            </table>
        </div>
        {% include 'inc/custom_fields_panel.html' with obj=secret %}
	</div>
	<div class="col-md-6">
        {% if secret|decryptable_by:request.user %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Secret Data</strong>
                </div>
                <div class="panel-body">
                    <form id="secret_form">
                        {% csrf_token %}
                    </form>
                    <div class="row">
                        <div class="col-md-2">Secret</div>
                        <div class="col-md-6" id="secret_{{ secret.pk }}">********</div>
                        <div class="col-md-4 text-right noprint">
                            <button class="btn btn-xs btn-success unlock-secret" secret-id="{{ secret.pk }}">
                                <i class="fa fa-lock"></i> Unlock
                            </button>
                            <button class="btn btn-xs btn-default copy-secret collapse" secret-id="{{ secret.pk }}" data-clipboard-target="#secret_{{ secret.pk }}">
                                <i class="fa fa-copy"></i> Copy
                            </button>
                            <button class="btn btn-xs btn-danger lock-secret collapse" secret-id="{{ secret.pk }}">
                                <i class="fa fa-unlock-alt"></i> Lock
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-warning">
                <i class="fa fa-warning" aria-hidden="true"></i>
                You do not have permission to decrypt this secret.
            </div>
        {% endif %}
        {% include 'extras/inc/tags_panel.html' with tags=secret.tags.all url='secrets:secret_list' %}
    </div>
</div>

{% include 'secrets/inc/private_key_modal.html' %}
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}

netbox/templates/secrets/secret_delete.html
{% extends 'utilities/confirmation_form.html' %}
{% load form_helpers %}

{% block title %}Delete secret {{ secret }}?{% endblock %}

{% block message %}
    <p>Are you sure you want to delete secret {{ secret }}?</p>
{% endblock %}

netbox/templates/secrets/secret_edit.html
{% extends '_base.html' %}
{% load static %}
{% load form_helpers %}

{% block content %}
<form action="." method="post" class="form form-horizontal">
    {% csrf_token %}
    {{ form.private_key }}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h3>{% block title %}{% if secret.pk %}Editing {{ secret }}{% else %}Add a Secret{% endif %}{% endblock %}</h3>
            {% if form.non_field_errors %}
                <div class="panel panel-danger">
                    <div class="panel-heading"><strong>Errors</strong></div>
                    <div class="panel-body">
                        {{ form.non_field_errors }}
                    </div>
                </div>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Secret Attributes</strong></div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label required">Device</label>
                        <div class="col-md-9">
                            <p class="form-control-static">{{ secret.device }}</p>
                        </div>
                    </div>
                    {% render_field form.role %}
                    {% render_field form.name %}
                    {% render_field form.userkeys %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Secret Data</strong></div>
                <div class="panel-body">
                    {% if secret.pk %}
                        <div class="form-group">
                            <label class="col-md-3 control-label required">Current Plaintext</label>
                            <div class="col-md-7">
                                <p class="form-control-static" id="secret_{{ secret.pk }}">********</p>
                            </div>
                            <div class="col-md-2 text-right">
                                <button class="btn btn-xs btn-success unlock-secret" secret-id="{{ secret.pk }}">
                                    <i class="fa fa-lock"></i> Unlock
                                </button>
                                <button class="btn btn-xs btn-danger lock-secret collapse" secret-id="{{ secret.pk }}">
                                    <i class="fa fa-unlock-alt"></i> Lock
                                </button>
                            </div>
                        </div>
                    {% endif %}
                    {% render_field form.plaintext %}
                    {% render_field form.plaintext2 %}
                </div>
            </div>
            {% if form.custom_fields %}
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Custom Fields</strong></div>
                    <div class="panel-body">
                        {% render_custom_fields form %}
                    </div>
                </div>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Tags</strong></div>
                <div class="panel-body">
                    {% render_field form.tags %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <div class="col-md-12 text-center">
                {% if secret.pk %}
                    <button type="submit" name="_update" class="btn btn-primary">Update</button>
                    <a href="{% url 'secrets:secret' pk=secret.pk %}" class="btn btn-default">Cancel</a>
                {% else %}
                    <button type="submit" name="_create" class="btn btn-primary">Create</button>
                    <button type="submit" name="_addanother" class="btn btn-primary">Create and Add Another</button>
                    <a href="{{ return_url }}" class="btn btn-default">Cancel</a>
                {% endif %}
		    </div>
        </div>
    </div>
</form>

{% include 'secrets/inc/private_key_modal.html' %}
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}

netbox/templates/secrets/secret_import.html
{% extends 'utilities/obj_import.html' %}
{% load static %}

{% block content %}
{{ block.super }}
{% include 'secrets/inc/private_key_modal.html' %}
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}

netbox/templates/secrets/secret_list.html
{% extends '_base.html' %}
{% load buttons %}

{% block content %}
<div class="pull-right noprint">
    {% if perms.secrets.add_secret %}
        {% import_button 'secrets:secret_import' %}
    {% endif %}
    {% export_button content_type %}
</div>
<h1>{% block title %}Secrets{% endblock %}</h1>
<div class="row">
    <div class="col-md-9">
        {% include 'utilities/obj_table.html' with bulk_edit_url='secrets:secret_bulk_edit' bulk_delete_url='secrets:secret_bulk_delete' %}
    </div>
    <div class="col-md-3 noprint">
		{% include 'inc/search_panel.html' %}
		{% include 'inc/tags_panel.html' %}
    </div>
</div>
{% endblock %}

netbox/templates/secrets/secretrole_list.html
{% extends '_base.html' %}
{% load buttons %}

{% block content %}
<div class="pull-right noprint">
    {% if perms.secrets.add_secretrole %}
        {% add_button 'secrets:secretrole_add' %}
        {% import_button 'secrets:secretrole_import' %}
    {% endif %}
    {% export_button content_type %}
</div>
<h1>{% block title %}Secret Roles{% endblock %}</h1>
<div class="row">
	<div class="col-md-12">
        {% include 'utilities/obj_table.html' with bulk_delete_url='secrets:secretrole_bulk_delete' %}
    </div>
</div>
{% endblock %}